### ISSUE TITLE
Partials-in-partials

### ISSUE THREAD

**Issue by zaceno** [zaceno/hyperapp-partial#2]
Note to self: make partials support partials to be mixied in.

Best not to call it mixins though. Perhaps "partials".

Probably not too tricky. But is it a good idea?

**Comment by zaceno** [comment]
Done, since 0.4.0

**Comment by jbucaran** [comment]
I was too late to the party, but I would have said: I'd like to see them first before creating an opinion. Good thing you got this done.

**Comment by zaceno** [comment]
@jbucaran: no problem you were late -- it was a very lonely party anyway ;) But yeah you're right, it's best to have something to try out before knowing if it's worth doing or not. As it turns out, I found a use-case for it, so I built it, and am about to try it now. I'll report back how it goes.
